# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vue CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-22.04
        
    steps:
    # check out the latest commit
    - uses: actions/checkout@v4
    
    # set up node environment
    - name: setup Node 
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    # install dependencies
    - name: install
      run: npm install

    # build project
    - name: build
      run: npm run build

    # clean leftover
    - name: Clean up
      run: |
        find . -type f ! -path './dist/*' -delete
        find . -type d ! -path './dist' -exec rm -rf {} +
        
    # connect to the server and deploy
    - name: deploy
      uses: easingthemes/ssh-deploy@v5.1.0
      with: 
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        REMOTE_HOST: ${{secrets.SERVER_HOST}}
        REMOTE_USER: ${{secrets.SERVER_USER}}
        TARGET: /home/ubuntu/picnia-dist/dist # target to server root
    
